---
name: GHDL Testbench
on: [push]
jobs:
  Execute-Testbench:
    runs-on: ubuntu-latest
    steps:
      - uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: llvm
      - run: ghdl --version
