---
env:
  PROJECT_TB_NAME: helloled_tb

name: GHDL Testbench
on: [push]
jobs:
  Execute-Testbench:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GHDL nightly
        uses: ghdl/setup-ghdl-ci@nightly
      - run: ghdl --version
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Execute the VHDL testbench
        run: |
          ghdl -a src/hdl/*.vhd
          ghdl -e src/hdl/$PROJECT_TB_NAME
          ghdl -r src/hdl/$PROJECT_TB_NAME
